# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'video-api'
    static_configs:
      - targets: ['video-api:3000']
    metrics_path: '/metrics'

  - job_name: 'video-worker'
    static_configs:
      - targets: ['video-worker:9091']
    metrics_path: '/metrics'
